name: Rasa Data Validate

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rasa Train-Test Model GitHub Action
        uses: RasaHQ/rasa-train-test-gha@2.0.0
        with:
          rasa_version: "2.8.25"
          rasa_train: false
